set(ASSIMP_ROOT "D:/Libraries/packages/assimp-3.1.1")

set(ASSIMP_INCLUDE_DIRS "" CACHE PATH "" FORCE)

set(ASSIMP_LIBRARY_DIRS_DEBUG ${ASSIMP_ROOT}/lib CACHE PATH "" FORCE)
set(ASSIMP_LIBRARY_DIRS_RELEASE ${ASSIMP_ROOT}/lib CACHE PATH "" FORCE)

set(ASSIMP_LIBRARY_FILES_DEBUG assimp CACHE STRING "" FORCE)
set(ASSIMP_LIBRARY_FILES_RELEASE assimp CACHE STRING "" FORCE)

set(ASSIMP_CXX_FLAGS "" CACHE STRING "" FORCE)
set(ASSIMP_CXX_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(ASSIMP_CXX_FLAGS_RELEASE "" CACHE STRING "" FORCE)

set(ASSIMP_LINK_FLAGS "" CACHE STRING "" FORCE)
set(ASSIMP_LINK_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(ASSIMP_LINK_FLAGS_RELEASE "" CACHE STRING "" FORCE)
