set(SDL_ROOT "D:/Libraries/packages/sdl-2.0.3")

set(SDL_INCLUDE_DIRS "" CACHE PATH "" FORCE)

set(SDL_LIBRARY_DIRS_DEBUG ${SDL_ROOT}/lib CACHE PATH "" FORCE)
set(SDL_LIBRARY_DIRS_RELEASE ${SDL_ROOT}/lib CACHE PATH "" FORCE)

set(SDL_LIBRARY_FILES_DEBUG SDL2 CACHE STRING "" FORCE)
set(SDL_LIBRARY_FILES_RELEASE SDL2 CACHE STRING "" FORCE)

set(SDL_CXX_FLAGS "" CACHE STRING "" FORCE)
set(SDL_CXX_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(SDL_CXX_FLAGS_RELEASE "" CACHE STRING "" FORCE)

set(SDL_LINK_FLAGS "" CACHE STRING "" FORCE)
set(SDL_LINK_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(SDL_LINK_FLAGS_RELEASE "" CACHE STRING "" FORCE)
