set(GTEST_INCLUDE_DIRS "" CACHE PATH "" FORCE)

set(GTEST_LIBRARY_DIRS_DEBUG "" CACHE PATH "" FORCE)
set(GTEST_LIBRARY_DIRS_RELEASE "" CACHE PATH "" FORCE)

set(GTEST_LIBRARY_FILES_DEBUG gtest CACHE STRING "" FORCE)
set(GTEST_LIBRARY_FILES_RELEASE gtest CACHE STRING "" FORCE)

set(GTEST_CXX_FLAGS "" CACHE STRING "" FORCE)
set(GTEST_CXX_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(GTEST_CXX_FLAGS_RELEASE "" CACHE STRING "" FORCE)

set(GTEST_LINK_FLAGS "" CACHE STRING "" FORCE)
set(GTEST_LINK_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(GTEST_LINK_FLAGS_RELEASE "" CACHE STRING "" FORCE)
