set(ASSIMP_INCLUDE_DIRS "" CACHE PATH "" FORCE)

set(ASSIMP_LIBRARY_DIRS_DEBUG "" CACHE PATH "" FORCE)
set(ASSIMP_LIBRARY_DIRS_RELEASE "" CACHE PATH "" FORCE)

set(ASSIMP_LIBRARY_FILES_DEBUG assimp CACHE STRING "" FORCE)
set(ASSIMP_LIBRARY_FILES_RELEASE assimp CACHE STRING "" FORCE)

set(ASSIMP_CXX_FLAGS "" CACHE STRING "" FORCE)
set(ASSIMP_CXX_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(ASSIMP_CXX_FLAGS_RELEASE "" CACHE STRING "" FORCE)

set(ASSIMP_LINK_FLAGS "" CACHE STRING "" FORCE)
set(ASSIMP_LINK_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(ASSIMP_LINK_FLAGS_RELEASE "" CACHE STRING "" FORCE)
