set(BOOST_INCLUDE_DIRS "" CACHE PATH "" FORCE)

set(BOOST_LIBRARY_DIRS_DEBUG "" CACHE PATH "" FORCE)
set(BOOST_LIBRARY_DIRS_RELEASE "" CACHE PATH "" FORCE)

set(BOOST_LIBRARY_FILES_DEBUG gtest
	boost_iostreams
	boost_filesystem
	boost_serialization
	boost_system
	boost_thread
	CACHE STRING "" FORCE)

set(BOOST_LIBRARY_FILES_RELEASE ${BOOST_LIBRARY_FILES_DEBUG} CACHE STRING "" FORCE)

set(BOOST_CXX_FLAGS "" CACHE STRING "" FORCE)
set(BOOST_CXX_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(BOOST_CXX_FLAGS_RELEASE "" CACHE STRING "" FORCE)

set(BOOST_LINK_FLAGS "" CACHE STRING "" FORCE)
set(BOOST_LINK_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(BOOST_LINK_FLAGS_RELEASE "" CACHE STRING "" FORCE)
